// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/Shubham23jha/go-gin-postgres-clean/internal/handlers"
	"github.com/Shubham23jha/go-gin-postgres-clean/internal/repository"
	"github.com/Shubham23jha/go-gin-postgres-clean/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*App, error) {
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	userService := service.NewUserService(userRepository, sessionRepository)
	sessionService := service.NewSessionService(sessionRepository)
	authHandler := handlers.NewAuthHandler(userService, sessionService)
	campaignRepository := repository.NewCampaignRepository(db)
	campaignService := service.NewCampaignService(campaignRepository)
	campaignHandler := handlers.NewCampaignHandler(campaignService)
	outboxPublisher := service.NewOutboxPublisher(campaignRepository, "amqp://guest:guest@localhost:5672/")
	workerPool := service.NewWorkerPool(campaignRepository, "amqp://guest:guest@localhost:5672/", 5) // 5 concurrent workers
	app := NewApp(authHandler, campaignHandler, outboxPublisher, workerPool)
	return app, nil
}
