// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

// Package bootstrap handles the application initialization and dependency injection.
package bootstrap

import (
	"github.com/Shubham23jha/digital-post-office/internal/handlers"
	"github.com/Shubham23jha/digital-post-office/internal/repository"
	"github.com/Shubham23jha/digital-post-office/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*App, error) {
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	userService := service.NewUserService(userRepository, sessionRepository)
	sessionService := service.NewSessionService(sessionRepository)
	authHandler := handlers.NewAuthHandler(userService, sessionService)
	campaignRepository := repository.NewCampaignRepository(db)
	campaignService := service.NewCampaignService(campaignRepository)
	campaignHandler := handlers.NewCampaignHandler(campaignService)
	string2 := service.ProvideRabbitMQURL()
	outboxPublisher := service.NewOutboxPublisher(campaignRepository, string2)
	int2 := _wireIntValue
	workerPool := service.NewWorkerPool(campaignRepository, string2, int2)
	app := NewApp(authHandler, campaignHandler, outboxPublisher, workerPool)
	return app, nil
}

var (
	_wireIntValue = 5
)
