apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
      - name: email-api
        image: digital-post-office:v1
        imagePullPolicy: IfNotPresent
        command: ["./api-server"]
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: email-system-config
        - secretRef:
            name: email-system-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: email-api
spec:
  selector:
    app: email-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
