apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: email-worker-scaler
spec:
  scaleTargetRef:
    name: email-worker # Must match the Deployment name
  minReplicaCount: 0 # Save money/resources when queue is empty!
  maxReplicaCount: 10 # Scale up to 10 workers during peaks
  triggers:
  - type: rabbitmq
    metadata:
      queueName: email_queue
      host: amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/ # FQDN for cross-namespace access
      mode: QueueLength
      value: "2" # Scale up for every 2 messages in the queue (for better visualization)
