apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-publisher
  template:
    metadata:
      labels:
        app: email-publisher
    spec:
      containers:
      - name: email-publisher
        image: digital-post-office:v1
        imagePullPolicy: IfNotPresent
        command: ["./publisher"]
        envFrom:
        - configMapRef:
            name: email-system-config
        - secretRef:
            name: email-system-secrets
